package com.demo.EmployeeRegistration.entity;
import jakarta.persistence.*;
import lombok.*;

/**
 * User Entity for Authentication
 *
 * PURPOSE (Week 4 Lab):
 * Stores user credentials for authentication
 * Used to validate username and password during login
 *
 * SECURITY NOTES:
 * - In production, passwords must be hashed (BCrypt)
 * - Never store plain text passwords
 * - This example uses plain text for lab simplicity
 *
 * TABLE STRUCTURE:
 * CREATE TABLE users (
 *     id BIGINT PRIMARY KEY AUTO_INCREMENT,
 *     username VARCHAR(255) UNIQUE NOT NULL,
 *     password VARCHAR(255) NOT NULL,
 *     role VARCHAR(50)
 * )
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Primary Key
     * Auto-generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Username for authentication
     * Must be unique (one user per username)
     * LAB REQUIREMENT: Used for login API
     */
    @Column(nullable = false, unique = true)
    private String username;

    /**
     * Password for authentication
     * LAB NOTE: Stored as plain text for simplicity
     * PRODUCTION: Must use password encoder (BCrypt)
     * LAB REQUIREMENT: Used for login API validation
     */
    @Column(nullable = false)
    private String password;

    /**
     * User role (e.g., "USER", "ADMIN")
     * Used for role-based access control
     * Optional for basic lab requirements
     */
    @Column(nullable = false)
    private String role = "USER";
}